name: Test action

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Restart server
        uses: hwalker928/ptero-gitsync@v0.3
        with:
          panel-url: ${{ secrets.PANEL_URL }}
          api-key: ${{ secrets.API_KEY }}
          server-id: ${{ secrets.SERVER_ID }}
