name: Test

on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test script
        uses: hwalker928/ptero-gitsync@v1.1
        with:
          example-input: "this is an example"
